test_that("annotation.pos.utils", {
  chr <- c("chr1", "chr2", "chr1")
  start <- c("10020", "10020", "10020")
  end <- c("10020", "10020", "10020")
  ref <- c("A", "A", "A")
  alt <- c("-", "-", "-")
  database <- system.file("extdata", "demo/hg19_avsnp147.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation.pos.utils(dat.list, "avsnp147", database.dir = database.dir, 
    return.col.names = "avSNP147")
  expect_that(colnames(x), equals("avSNP147"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("rs775809821"))
  expect_that(is.na(x[2, 1]), equals(TRUE))
  expect_that(x[3, 1], equals("rs775809821"))
  x <- annotation.pos.utils(dat.list, "avsnp147", database.dir = database.dir, 
    return.col.names = "avSNP147", db.type = "txt")
  expect_that(colnames(x), equals("avSNP147"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("rs775809821"))
  expect_that(is.na(x[2, 1]), equals(TRUE))
  expect_that(x[3, 1], equals("rs775809821"))
})

test_that("annotation.snp", {
  chr <- c("chr1", "chr2", "chr1")
  start <- c("10020", "10020", "10020")
  end <- c("10020", "10020", "10020")
  ref <- c("A", "A", "A")
  alt <- c("-", "-", "-")
  database <- system.file("extdata", "demo/hg19_avsnp147.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation.snp(dat.list = dat.list, name = "avsnp147", database.dir = database.dir)
  expect_that(colnames(x), equals("avSNP147"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("rs775809821"))
  expect_that(is.na(x[2, 1]), equals(TRUE))
  expect_that(x[3, 1], equals("rs775809821"))
})

test_that("annotation.cosmic", {
  chr <- c("chr12", "chr2", "chr12")
  start <- c("11139001", "50850617", "11139002")
  end <- c("11139001", "50850617", "50850617")
  ref <- c("C", "G", "T")
  alt <- c("T", "A", "-")
  database <- system.file("extdata", "demo/hg19_cosmic81.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation.cosmic(dat.list = dat.list, name = "cosmic81", database.dir = database.dir)
  expect_that(colnames(x), equals("COSMIC_81"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("ID=COSM4732228;OCCURENCE=1(large_intestine)"))
  expect_that(x[2, 1], equals("ID=COSM383974,COSM5973818,COSM383973,COSM5973817;OCCURENCE=1(upper_aerodigestive_tract),1(lung)"))
  expect_that(is.na(x[3, 1]), equals(TRUE))
})

test_that("annotation.1000g", {
  chr <- c("chr1", "chr2", "chr1")
  start <- c("10177", "10177", "10020")
  end <- c("10177", "10177", "10020")
  ref <- c("-", "A", "A")
  alt <- c("C", "AC", "-")
  database <- system.file("extdata", "demo/hg19_ALL.sites.2015_08.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation.1000g(dat.list = dat.list, name = "1000g2015aug_all", database.dir = database.dir)
  expect_that(colnames(x), equals("frq"))
  x <- annotation.1000g(dat.list = dat.list, name = "1000g2015aug_all", database.dir = database.dir, 
    return.col.names = "1000g2015aug_all")
  expect_that(colnames(x), equals("1000g2015aug_all"))
})

test_that("annotation:1000g", {
  chr <- c("chr1", "chr2", "chr1")
  start <- c("10177", "10177", "10020")
  end <- c("10177", "10177", "10020")
  ref <- c("-", "A", "A")
  alt <- c("C", "AC", "-")
  database <- system.file("extdata", "demo/hg19_ALL.sites.2015_08.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation(dat.list = dat.list, name = "1000g2015aug_all", database.dir = database.dir)
  expect_that(colnames(x), equals("frq"))
  x <- annotation(dat.list = dat.list, name = "1000g2015aug_all", database.dir = database.dir, 
    return.col.names = "1000g2015aug_all")
  expect_that(colnames(x), equals("1000g2015aug_all"))
})

test_that("annotation:cosmic", {
  chr <- c("chr12", "chr2", "chr12")
  start <- c("11139001", "50850617", "11139002")
  end <- c("11139001", "50850617", "50850617")
  ref <- c("C", "G", "T")
  alt <- c("T", "A", "-")
  database <- system.file("extdata", "demo/hg19_cosmic81.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation(dat.list = dat.list, name = "cosmic81", database.dir = database.dir)
  expect_that(colnames(x), equals("COSMIC_81"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("ID=COSM4732228;OCCURENCE=1(large_intestine)"))
  expect_that(x[2, 1], equals("ID=COSM383974,COSM5973818,COSM383973,COSM5973817;OCCURENCE=1(upper_aerodigestive_tract),1(lung)"))
  expect_that(is.na(x[3, 1]), equals(TRUE))
})

test_that("annotation:snp", {
  chr <- c("chr1", "chr2", "chr1")
  start <- c("10020", "10020", "10020")
  end <- c("10020", "10020", "10020")
  ref <- c("A", "A", "A")
  alt <- c("-", "-", "-")
  database <- system.file("extdata", "demo/hg19_avsnp147.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation(dat.list = dat.list, name = "avsnp147", database.dir = database.dir)
  expect_that(colnames(x), equals("avSNP147"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("rs775809821"))
  expect_that(is.na(x[2, 1]), equals(TRUE))
  expect_that(x[3, 1], equals("rs775809821"))
})


test_that("annotation:RNA-editing", {
  # RADAR2
  chr <- c("1", "6", "1")
  start <- c("206256301", "116991832", "10020")
  database <- system.file("extdata", "demo/hg19_RADAR2.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start)
  x <- annotation(dat.list = dat.list, name = "RADAR2", database.dir = database.dir)
  expect_that(colnames(x), equals("RADAR2.is.alu"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("no"))
  expect_that(x[2, 1], equals("no"))
  expect_that(is.na(x[3, 1]), equals(TRUE))
  
  # DAREND
  chr <- c("4", "4", "1")
  start <- c("250721", "475468", "10020")
  database <- system.file("extdata", "demo/hg19_DARNED.sqlite", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start)
  x <- annotation(dat.list = dat.list, name = "DARNED", database.dir = database.dir)
  expect_that(colnames(x), equals("DARNED.in.rna"))
  x[, 1] <- as.character(x[, 1])
  expect_that(x[1, 1], equals("I"))
  expect_that(x[2, 1], equals("I"))
  expect_that(is.na(x[3, 1]), equals(TRUE))
})

test_that("annotation.normal.pool", {
  chr <- c("chr1", "chr1", "chr1")
  start <- c("13183511", "13183528", "10020")
  end <- c("13183511", "13183528", "10020")
  ref <- c("T", "A", "A")
  alt <- c("C", "C", "-")

  database <- system.file("extdata", "demo/hg19_normal2016sih_wes_ball.txt", package = "annovarR")
  database.dir <- dirname(database)
  dat.list <- list(chr = chr, start = start, end = end, ref = ref, alt = alt)
  x <- annotation(dat.list = dat.list, name = "2016sih_wes_ball", database.dir = database.dir)
  expect_that(colnames(x), equals("2016sih_wes_ball"))
  x[, 1] <- as.numeric(x[, 1])
  expect_that(x[1, 1], equals(200))
  expect_that(x[2, 1], equals(200))
  expect_that(is.na(x[3, 1]), equals(TRUE))
  x <- annotation(dat.list = dat.list, name = "2016sih_wes_nkt", database.dir = database.dir)
  expect_that(colnames(x), equals("2016sih_wes_nkt"))
  x[, 1] <- as.numeric(x[, 1])
  expect_that(x[1, 1], equals(25))
  expect_that(x[2, 1], equals(25))
  expect_that(is.na(x[3, 1]), equals(TRUE))
  x <- annotation(dat.list = dat.list, name = "2016sih_wgs_nkt", database.dir = database.dir)
  expect_that(colnames(x), equals("2016sih_wgs_nkt"))
  x[, 1] <- as.numeric(x[, 1])
  expect_that(x[1, 1], equals(10))
  expect_that(x[2, 1], equals(10))
  expect_that(is.na(x[3, 1]), equals(TRUE))
  x <- annotation(dat.list = dat.list, name = "2016sih_wgs_dlbcl", database.dir = database.dir)
  expect_that(colnames(x), equals("2016sih_wgs_dlbcl"))
  x[, 1] <- as.numeric(x[, 1])
  expect_that(x[1, 1], equals(16))
  expect_that(x[2, 1], equals(16))
  expect_that(is.na(x[3, 1]), equals(TRUE))
})
