test_that("select.dat.region.match.txt", {
  bed.file <- system.file("extdata", "demo/example.bed", package = "annovarR")
  V1 <- c("chr10", "chr1")
  V2 <- c("100188904", "100185955")
  V3 <- c("100188904", "100185955")
  params <- list(V1 = V1, V2 = V2, V3 = V3)
  x <- select.dat.region.match(bed.file, "bed", "V1", "V2", "V3", params = params, 
    db.type = "txt")
  x <- as.data.frame(x)
  expect_that(nrow(x), equals(2))
  expect_that(x[1, 1], equals("chr10"))
  expect_that(x[2, 1], equals("chr10"))
  expect_that(x[1, 4], equals("HPS1"))
  expect_that(x[2, 4], equals("HPS1"))
})

test_that("select.dat.region.match.sqlite", {
  bed.file <- system.file("extdata", "demo/example.bed", package = "annovarR")
  bed.sqlite <- sprintf("%s/%s.sqlite", tempdir(), basename(bed.file))
  connect.params <- list(dbname = bed.sqlite, table.name = "bed")
  sqlite.build(bed.file, connect.params)
  expect_that(file.size(bed.sqlite) > 0, equals(TRUE))
  V1 <- c("chr10", "chr1")
  V2 <- c("100188904", "100185955")
  V3 <- c("100188904", "100185955")
  params <- list(V1 = V1, V2 = V2, V3 = V3)
  con <- dbConnect(SQLite(), bed.sqlite)
  x <- select.dat.region.match(con, "bed", "V1", "V2", "V3", params = params, db.type = "sqlite", 
    verbose = FALSE)
  dbDisconnect(con)
  x <- as.data.frame(x)
  expect_that(nrow(x), equals(2))
  expect_that(x[1, 1], equals("chr10"))
  expect_that(x[2, 1], equals("chr10"))
  expect_that(x[1, 4], equals("HPS1"))
  expect_that(x[2, 4], equals("HPS1"))
  file.remove(bed.sqlite)
  
})

test_that("annotation.region.match", {
  bed.file <- system.file("extdata", "demo/example.bed", package = "annovarR")
  bed.sqlite <- sprintf("%s/%s.sqlite", tempdir(), basename(bed.file))
  connect.params <- list(dbname = bed.sqlite, table.name = "bed")
  sqlite.build(bed.file, connect.params)
  expect_that(file.size(bed.sqlite) > 0, equals(TRUE))
  chr <- c("chr10", "chr1")
  start <- c("100188904", "100185955")
  end <- c("100188904", "100185955")
  dat <- data.table(chr = chr, start = start, end = end)
  x <- annotation.region.match(dat = dat, database.dir = tempdir(), dbname.fixed = bed.sqlite, 
    table.name.fixed = "bed", db.type = "sqlite", format.dat.fun = format.cols.plus.chr)
  x <- as.data.frame(x)
  expect_that(x[1, 1], equals("HPS1"))
  expect_that(is.na(x[2, 1]), equals(TRUE))
})
