test_that("download.database", {
  demo.cfg <- system.file("extdata", "demo/demo.cfg", package = "annovarR")
  x <- download.database("download_demo", show.all.versions = T, database.cfg = demo.cfg)
  expect_that(x, equals("demo"))
  database.dir <- sprintf("%s/databases/", tempdir())
  file.remove(sprintf("%s/%s", database.dir, list.files(database.dir, ".*")))
  x <- download.database("download_demo", "demo", buildver = "GRCh37", database.dir = database.dir,
    database.cfg = demo.cfg)
  expect_that(x, equals(TRUE))
  finalfn <- sprintf("%s/databases/GRCh37_MT_ensGene.txt", tempdir())
  x <- file.exists(finalfn)
  expect_that(x, equals(TRUE))
  x <- file.size(finalfn)
  expect_that(x > 0, equals(TRUE))
})
